#!/usr/bin/env bash
#
# gen-sitemap.sh — авто-генерація website/sitemap.xml для HeyCoach
# ----------------------------------------------------------------------------
# Сканує website/*.html, відкидає чернетки (список нижче) і будує sitemap.xml
# з <loc>https://heycoachproduction.de/<file></loc> + <lastmod>=сьогодні.
#
# USAGE:
#   bash scripts/gen-sitemap.sh            # запускати з кореня website/
#   (або)  bash website/scripts/gen-sitemap.sh
#
# Скрипт сам визначає корінь website/ відносно власного розташування, тож
# працює з будь-якого CWD. Виводить кількість публічних URL у stderr.
#
# Домен: heycoachproduction.de | GitHub Pages, branch main | Cloudflare
# ----------------------------------------------------------------------------
set -euo pipefail

# === ВИКЛЮЧЕННЯ (чернетки) — РЕДАГУЙ ТУТ ====================================
# basename-патерни (bash globbing, case-insensitive). Файл, що збігається з
# будь-яким патерном, у sitemap НЕ потрапляє. Додавай/прибирай рядки вільно.
EXCLUDE_PATTERNS=(
  'index-v[0-9]*.html'   # index-v3 .. index-v7 (чернетки головної)
  'index2.html'          # альт головна
  'index-print.html'     # друкована версія
  'hero-video.html'      # відео-демо
  'palette*.html'        # палітри кольорів
  'rollup*.html'         # rollup-mockups / rollup-all-concepts
  'spline-demo.html'     # 3D-демо
  'flyer-banner.html'    # флаєр/банер
  'kurs-guertel.html'    # стара версія (актуальна: kurs-guertel-v2)
  'kurs-kickboxen.html'  # стара версія (актуальна: kurs-kickboxen-v2)
  'kurs-marlon-v2.html'  # старі версії курсу Marlon
  'kurs-marlon-v3.html'
  'trainer-team.html'    # службова збірна сторінка
)
# ===========================================================================

# --- Визначаємо корінь website/ (батько теки scripts/) ---------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SITE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$SITE_DIR/sitemap.xml"
DOMAIN="https://heycoachproduction.de"
TODAY="$(date +%F)"   # YYYY-MM-DD

# --- Чи виключений файл? ----------------------------------------------------
is_excluded() {
  local base="$1" pat
  shopt -s nocasematch
  for pat in "${EXCLUDE_PATTERNS[@]}"; do
    # shellcheck disable=SC2053
    if [[ "$base" == $pat ]]; then shopt -u nocasematch; return 0; fi
  done
  shopt -u nocasematch
  return 1
}

# --- Пишемо sitemap ---------------------------------------------------------
{
  echo '<?xml version="1.0" encoding="UTF-8"?>'
  echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"'
  echo '        xmlns:xhtml="http://www.w3.org/1999/xhtml">'
  echo ''
  echo '    <!-- Auto-generated by scripts/gen-sitemap.sh — НЕ редагувати вручну -->'
  echo ''

  # Homepage окремо: index.html → канонічний "/"
  echo '    <url>'
  echo "        <loc>$DOMAIN/</loc>"
  echo "        <lastmod>$TODAY</lastmod>"
  echo '        <changefreq>weekly</changefreq>'
  echo '        <priority>1.0</priority>'
  echo '    </url>'
  echo ''
} > "$OUT"

count=1   # homepage уже додано

while IFS= read -r f; do
  base="$(basename "$f")"
  [[ "$base" == "index.html" ]] && continue   # вже додано як "/"
  if is_excluded "$base"; then continue; fi
  {
    echo '    <url>'
    echo "        <loc>$DOMAIN/$base</loc>"
    echo "        <lastmod>$TODAY</lastmod>"
    echo '        <changefreq>monthly</changefreq>'
    echo '        <priority>0.8</priority>'
    echo '    </url>'
  } >> "$OUT"
  count=$((count + 1))
done < <(find "$SITE_DIR" -maxdepth 1 -name '*.html' | sort)

echo '' >> "$OUT"
echo '</urlset>' >> "$OUT"

echo "✅ sitemap.xml згенеровано: $OUT" >&2
echo "   Публічних URL: $count (lastmod=$TODAY)" >&2
# Машинно-читабельний рядок для hook'ів/CI:
echo "PUBLIC_URLS=$count"
